apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Donkey
  description: Donkey
  tags:
    - go
    - donkeys
  links:
    - url: https://github.com/shukibakbuki/donkey

spec:
  type: repo
  lifecycle: production
  owner: team-a
  system: artist-engagement-portal
